apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets
  - istiod
  - istio-gateway
  - flux-monitoring
  - grafana-virtualservice.yaml
  - flux-dashboard-14937.yaml
