apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Storage class must be first (used by prometheus stack)
  - storage-class
  # CRD providers
  - kube-prometheus-stack
  - istio-base
  # Then dependent resources
  - external-secrets
  - istiod
  - istio-gateway
