apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage-class
  - external-secrets
  # - kube-prometheus-stack  # Temporarily removed for recreation
  - istio-base
  - istiod
  - istio-gateway
