apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # CRD providers first
  - kube-prometheus-stack
  - istio-base
  # Then dependent resources
  - storage-class
  - external-secrets
  - istiod
  - istio-gateway
