apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Infrastructure components (monitoring, ingress, etc.)
resources:
  - istiod
  - istio-gateway
  - kiali
  - opentelemetry
  - tempo
  - loki
  - alloy
  - cert-manager-certificates.yaml
