apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: alertmanager-virtualservice
  namespace: monitoring
spec:
  hosts:
  - alertmanager.local
  gateways:
  - istio-system/common-gateway
  http:
  - route:
    - destination:
        host: monitoring-kube-prometheus-alertmanager
        port:
          number: 9093
