apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-virtualservice.yaml
  - prometheus-virtualservice.yaml
  - alertmanager-virtualservice.yaml
  - flux-dashboard-14937.yaml
  - flux-podmonitor.yaml
