apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: prometheus-virtualservice
  namespace: monitoring
spec:
  hosts:
  - prometheus.local
  gateways:
  - istio-system/common-gateway
  http:
  - route:
    - destination:
        host: monitoring-kube-prometheus-prometheus
        port:
          number: 9090
